export const posts = [
  {
    id: "pipos",
    titulo: "Por que castrar seu bichinho?",
    nome: "pipos",
    tags: ["educacional", "saúde", "castração"],
    caminho_imagem: "../img/animais_diversos.jpg",
    alt_imagem:
      "Vários animais em um fundo branco: Labrador Retriever Amarelo, Papagaio cinza, Gato malhado, Porquinho da Índia marrom e branco, Porco marrom escuro, Coelho preto e Jabuti Marrom.",
    texto:
      "A castração é essencial para a saúde e bem-estar dos pets, ajudando a prevenir doenças graves, como câncer de mama, útero e próstata...",
  },
  {
    id: "feirinha",
    titulo: "Feira de adoção na Praça do Mêtro Botafogo",
    endereco: "Praça Nelson Mandela",
    nome: "feirinha",
    tags: ["eventos", "adoção"],
    caminho_imagem: "../img/feira_adocao.jpg",
    alt_imagem: "Evento de adoção de animais na praça.",
    texto: "Venha conhecer e adotar um amigo!",
  },
  {
    id: "focinhos",
    titulo: "Feira de adoção na Praça do Mêtro Botafogo",
    endereco: "Rua Farani, 22",
    nome: "focinhos",
    tags: ["eventos", "adoção"],
    caminho_imagem: "../img/feira_adocao.jpg",
    alt_imagem: "Evento de adoção de animais.",
    texto: "Aproveite a chance de adotar um animal carente!",
  },
  {
    id: "pets",
    titulo: "Evento de adoção na petshop da felicidade",
    nome: "pets",
    endereco: "Rua Silva Freitas, 43",
    tags: ["eventos", "adoção"],
    caminho_imagem: "../img/petshop_evento.jpg",
    alt_imagem: "Petshop com evento de adoção de animais.",
    texto: "Não perca este evento de adoção!",
  },
  {
    id: "amigos-felizes",
    titulo: "Cuidados essenciais com seu cão",
    nome: "amigos-felizes",
    tags: ["educacional", "saúde"],
    caminho_imagem: "../img/cao_cuidados.jpg",
    alt_imagem: "Cachorro feliz correndo na grama.",
    texto: "Dicas de cuidados para manter seu cão saudável e feliz.",
  },
  {
    id: "animais-fantasticos",
    titulo: "Conheça os animais que vivem em nosso abrigo",
    nome: "animais-fantasticos",
    tags: ["educacional", "abrigo"],
    caminho_imagem: "../img/abrigo_animais.jpg",
    alt_imagem: "Animais diversos no abrigo.",
    texto: "Venha conhecer os animais que estão esperando um novo lar!",
  },
  {
    id: "gatinhos-fofos",
    titulo: "Os benefícios de adotar um gato",
    nome: "gatinhos-fofos",
    tags: ["educacional", "adoção", "gatos"],
    caminho_imagem: "../img/gatos.jpg",
    alt_imagem: "Gato deitado em uma cama.",
    texto: "Conheça as vantagens de ter um gato como animal de estimação.",
  },
  {
    id: "amigos-peludos",
    titulo: "Dicas de cuidados com a pelagem do seu pet",
    nome: "amigos-peludos",
    tags: ["educacional", "cuidados"],
    caminho_imagem: "../img/pelagem_pet.jpg",
    alt_imagem: "Cachorro sendo escovado.",
    texto: "Dicas para manter a pelagem do seu pet saudável.",
  },
  {
    id: "adesao-evento",
    titulo: "Participe da feira de adoção na praça central",
    nome: "adesao-evento",
    tags: ["eventos", "adoção"],
    caminho_imagem: "../img/feira_evento.jpg",
    alt_imagem: "Pessoas na feira de adoção.",
    texto: "Traga sua família e encontre um novo amigo!",
  },
  {
    id: "vacinas",
    titulo: "Vacinas essenciais para o seu pet",
    nome: "vacinas",
    tags: ["educacional", "saúde", "vacinação"],
    caminho_imagem: "../img/vacinacao.jpg",
    alt_imagem: "Veterinário aplicando vacina em um cachorro.",
    texto: "A importância de manter a vacinação do seu pet em dia.",
  },
  {
    id: "cuidados-gatos",
    titulo: "Cuidados com gatos idosos",
    nome: "cuidados-gatos",
    tags: ["educacional", "saúde", "gatos"],
    caminho_imagem: "../img/gato_idoso.jpg",
    alt_imagem: "Gato idoso descansando.",
    texto: "Dicas para cuidar bem dos gatos mais velhos.",
  },
  {
    id: "brincadeiras",
    titulo: "Brincadeiras para o seu cão",
    nome: "brincadeiras",
    tags: ["educacional", "diversão", "cães"],
    caminho_imagem: "../img/brincadeiras.jpg",
    alt_imagem: "Cachorro brincando com uma bola.",
    texto: "Atividades divertidas para manter seu cão ativo.",
  },
  {
    id: "alimentacao",
    titulo: "Como alimentar seu pet corretamente",
    nome: "alimentacao",
    tags: ["educacional", "alimentação", "saúde"],
    caminho_imagem: "../img/alimentacao_pet.jpg",
    alt_imagem: "Comida saudável para pets.",
    texto: "A importância de uma alimentação equilibrada.",
  },
  {
    id: "exercicio-gatos",
    titulo: "Exercícios para gatos domésticos",
    nome: "exercicio-gatos",
    tags: ["educacional", "exercício", "gatos"],
    caminho_imagem: "../img/gato_exercicio.jpg",
    alt_imagem: "Gato brincando com uma corda.",
    texto: "Como manter seu gato ativo e saudável.",
  },
  {
    id: "treinamento",
    titulo: "Dicas de treinamento para cachorros",
    nome: "treinamento",
    tags: ["educacional", "cães", "treinamento"],
    caminho_imagem: "../img/treinamento_cachorro.jpg",
    alt_imagem: "Cachorro sendo treinado.",
    texto: "Dicas para treinar e educar seu cão.",
  },
  {
    id: "lar-perfeito",
    titulo: "Preparando sua casa para um novo pet",
    nome: "lar-perfeito",
    tags: ["educacional", "adoção"],
    caminho_imagem: "../img/lar_pet.jpg",
    alt_imagem: "Casa preparada para receber um pet.",
    texto: "Dicas para preparar o lar para receber seu pet.",
  },
  {
    id: "adocao",
    titulo: "Feira de adoção: encontre um novo amigo",
    nome: "adocao",
    tags: ["eventos", "adoção"],
    caminho_imagem: "../img/feira_adocao_novo.jpg",
    alt_imagem: "Animais para adoção.",
    texto: "Adote um amigo e transforme sua vida!",
  },
  {
    id: "felicidade",
    titulo: "Como os pets trazem felicidade ao lar",
    nome: "felicidade",
    tags: ["educacional", "bem-estar", "pets"],
    caminho_imagem: "../img/felicidade_pet.jpg",
    alt_imagem: "Cachorro e gato juntos em casa.",
    texto: "Descubra os benefícios de ter um pet em casa.",
  },
  {
    id: "abrigo",
    titulo: "Visite nosso abrigo e conheça os animais",
    nome: "abrigo",
    tags: ["abrigo", "adoção"],
    caminho_imagem: "../img/abrigo.jpg",
    alt_imagem: "Animais esperando por adoção no abrigo.",
    texto: "Conheça nossos animais à espera de um lar.",
  },
  {
    id: "saude-mental",
    titulo: "Como os pets ajudam na saúde mental",
    nome: "saude-mental",
    tags: ["educacional", "bem-estar", "saúde mental"],
    caminho_imagem: "../img/pets_saude_mental.jpg",
    alt_imagem: "Pessoa interagindo com um cachorro.",
    texto: "Entenda os benefícios dos pets para a saúde mental.",
  },
];
